// news-data.js
// Dummy data 12 berita
const newsData = [
  {
    img: "img/cerydra.jpg",
    label: "Utama",
    title: "kaisar amphoreus wok",
    date: "4 september 2025",
    desc: "harmoby, wind,kaisar amphoreus, istri fathir",
  },
  {
    img: "img/hyasilens.jpg",
    label: "Utama",
    title: "tangan kanan cerydra",
    date: "tahun 1957 kalender cahaya",
    desc: "putriduyung dari laut amphoreus",
  },
  {
    img: "img/the-hertaLS.jpg",
    label: "Utama",
    title: "genius society #84",
    date: "tahun 1937 kalender cahaya",
    desc: "bini pertama fathir",
  },
  {
    img: "img/fireflykotak.jpeg",
    label: "Utama",
    title: "stellaron hunter",
    date: "tahun 2037 kalender cahaya",
    desc: "adek nya stella wok, anak kafka",
  },
  {
    img: "img/evernightkotak.jpg",
    label: "Utama",
    title: "marcht 7 th mode gelap",
    date: "tahun 2026 kalender cahaya",
    desc: "wujud asli marcht 7 th",
  },
  {
    img: "img/news6.jpg",
    label: "Utama",
    title: "Berita 6...",
    date: "17 Agustus 2025",
    desc: "Deskripsi berita 6 ...",
  },
  {
    img: "img/news7.jpg",
    label: "Utama",
    title: "Berita 7...",
    date: "16 Agustus 2025",
    desc: "Deskripsi berita 7 ...",
  },
  {
    img: "img/news8.jpg",
    label: "Utama",
    title: "Berita 8...",
    date: "16 Agustus 2025",
    desc: "Deskripsi berita 8 ...",
  },
  {
    img: "img/news9.jpg",
    label: "Utama",
    title: "Berita 9...",
    date: "15 Agustus 2025",
    desc: "Deskripsi berita 9 ...",
  },
  {
    img: "img/news10.jpg",
    label: "Utama",
    title: "Berita 10...",
    date: "15 Agustus 2025",
    desc: "Deskripsi berita 10 ...",
  },
  {
    img: "img/news11.jpg",
    label: "Utama",
    title: "Berita 11...",
    date: "14 Agustus 2025",
    desc: "Deskripsi berita 11 ...",
  },
  {
    img: "img/news12.jpg",
    label: "Utama",
    title: "Berita 12...",
    date: "14 Agustus 2025",
    desc: "Deskripsi berita 12 ...",
  },
  {
    img: "img/news12.jpg",
    label: "Utama",
    title: "Berita 12...",
    date: "14 Agustus 2025",
    desc: "Deskripsi berita 12 ...",
  },
];
